galaxy_info:
  author: Jared Hampson
  description: Install and configure fail2ban for Home Assistant Supervised

  license: MIT

  min_ansible_version: 2.9

  # Provide a list of supported platforms, and for each platform a list of versions.
  # If you don't wish to enumerate all versions for a particular platform, use 'all'.
  # To view available platforms and versions (or releases), visit:
  # https://galaxy.ansible.com/api/v1/platforms/
  #
  platforms:
    - name: Debian
      versions:
        - bullseye

  galaxy_tags:
    - home
    - assistant
    - supervised
    - raspberry
    - pi
    - hassio

dependencies: []
