---
- name: Install python package requirements for supervised_install
  apt:
    name:
      - python3-docker
    state: present
    update_cache: yes
  become: true

- name: Install OS package requirements for supervised_install # noqa 403
  apt:
    name:
      - debconf
      - debconf-utils
    state: latest
    update_cache: yes
  become: true
