galaxy_info:
  author: Jared Hampson
  description: Install Home Assistant Supervised
  role_name: supervised_install

  # If the issue tracker for your role is not on github, uncomment the
  # next line and provide a value
  # issue_tracker_url: http://example.com/issue/tracker

  license: MIT

  min_ansible_version: 2.9

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  #
  # Provide a list of supported platforms, and for each platform a list of versions.
  # If you don't wish to enumerate all versions for a particular platform, use 'all'.
  # To view available platforms and versions (or releases), visit:
  # https://galaxy.ansible.com/api/v1/platforms/
  #
  platforms:
    - name: Debian
      versions:
        - bullseye

  galaxy_tags:
    - smart
    - assistant
    - hassio
    - raspberry

dependencies:
  - geerlingguy.docker
